### ISSUE TITLE
Primarch abilities not handled correctly

### ISSUE THREAD

**Issue by ThePants999** [RosterizerTestData/Warhammer40k10e#3]
Primarchs all have an ability that lets them pick one of three other abilities in the command phase. Shinobau's parser is picking up the former as an "Other" ability, and creating a "Primarch" ability that contains the latter as subelements, but our parser isn't handling the subelements so you get an empty Primarch ability.

The ideal would be to add the three Primarch subabilities as traits of the "Other" ability. But it might not be worth updating the parser given there's one at most one Primarch ability per faction.

**Comment by TheGameKnave** [comment]
Solution: The three abilities will be created, but not assigned as there's not a great way to programmatically determine which ability to assign to (and daemonic allegiances get in the way). Any "primarch" abilities will also be listed int he text of the primarch as a reminder for maintainers to handle the inclusion.
Fixed in 10.0.6
