### ISSUE TITLE
Visual Bug: Anti- ability on weapons has an extra space

### ISSUE THREAD

**Issue by Mundangerous** [RosterizerTestData/Warhammer40k10e#38]
The Anti- ability is adding a space between "Anti-" and the Keyword stat.

Observed: Dark Angels > Ezekiel > Traitor's Bane is "Anti- chaos 2+"
Expected: Should be "Anti-chaos 2+"

Open question: should they Keyword be mixed case rather than lower? eg. Anti-Chaos vs Anti-chaos?

**Comment by TheGameKnave** [comment]
This has to do with the fact that, because users were including leading and trailing whitespace in fields, they were confusing the HELL out of themselves when their rules failed to work SO we trim leading and trailing whitespace in all input forms and thus space out all text modifications. We might be able to turn it off for cases like this, but it could potentially cause more problems than it would solve. I'll have to think on a solution.
Closing, as this is captured in the app defect tracker.
