### ISSUE TITLE
Space Marines: Chapter is not selectable from army header

### ISSUE THREAD

**Issue by Mundangerous** [RosterizerTestData/Warhammer40k10e#43]

**Comment by ThePants999** [comment]
I think this is intentional - and that fits with the way army building actually works. Technically, you don't choose a chapter, you just choose a detachment and units. There's simply a restriction that you can't have units from two chapters in the same list - so I think @TheGameKnave put in some logic such that once you put in the first chapter-locked unit, your list gets set to that chapter and units locked to other chapters get removed from the picker.

**Comment by TheGameKnave** [comment]
It *is* a little odd, though, if we're imagining putting SM together; a user is going to want to be able to select SW for instance, in order to restrict units they don't want, and define their detachment rules. Bears keeping in mind

**Comment by ThePants999** [comment]
Indeed, but - _are_ we putting SM together? The SM manifest is already barely usable without doubling its size...

**Comment by TheGameKnave** [comment]
plan for the best, whether it's immediately feasible or not. If we make it easy to integrate later while working correctly (or as expected) now, the work will be easier when it can be supported.

**Comment by ThePants999** [comment]
Well, I figure that should be as easy as making the stat dynamic then, right? If you've already got anything from the "wrong" chapter it'll complain they're not allowed.

**Comment by TheGameKnave** [comment]
Sort of. The stat has all the ranks for the splinter chapters, too, in order to let them "just work" when they import SM. I'd probably need to remove those ranks and add them one by one in the splinter chapter manifests.
