### ISSUE TITLE
Roster text view doesn't show you detachment

### ISSUE THREAD

**Issue by ThePants999** [RosterizerTestData/Warhammer40k10e#75]
Example of what it _does_ show you:

> [*Points*: **2000**, *Ally 1 Points*: **35**, *Faction*: **Adeptus Astartes**, *Chapter*: **Ultramarines**, *Allied faction 1*: **Agents of the Imperium**]

Detachment is needed and missing.

(Also, while I know you plan to support custom formatters in the future, that summary line really needs to be at the top - not the bottom - in the default formatter.)

**Comment by TheGameKnave** [comment]
@ThePants999  So, by default the text output will always show stats that are set to display "always", as well as any stats that are visibility "normal" AND have been changed from the default. I was keeping in mind future situations when the user will be able to define their detachment; the default will be "-" and any selection will deviate from that and show it.

I guess I was thinking that it wouldn't matter to show the detachment selection since there's currently no possible other choice. :)

**Comment by ThePants999** [comment]
Technically, no detachment rule at all is a legal choice (and the mandated one if you play a faction that doesn't have a detachment - titans or agents). Guess we go for "always".
